### ISSUE TITLE
Treatment of jobs with and without complete file information

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#4]
A treatment for jobs should follow the principle of equality. If they are same they should be treated as such. If they are different, they shouldn't be treated equal.

The latter is violated in the current treatment of the jobs, in the case when the file information is incomplete. According to @tfesenbecker they split only at the [connection module](https://github.com/tfesenbecker/lapis/blob/master/lapis/connection.py) in terms of treatment. This structure needs to be reconsidered.

I suggest to throw an exception or filter jobs with incomplete information. Any further suggestions or opinions?

**Comment by HerrHorizontal** [comment]
There might also be some interplay with the simulation monitoring and the job classes (see also issue #5).

**Comment by eileen-kuehn** [comment]
> A treatment for jobs should follow the principle of equality. If they are same they should be treated as such. If they are different, they shouldn't be treated equal.

What do you mean here? Do you mean equality of jobs in terms of `job_1 == job_2`? Otherwise in code given the perspective of a developer you want jobs to be treated as equal as possible to reduce the number of use cases you need to test and therefore possibly reduce the number of failures.

**Comment by HerrHorizontal** [comment]
I mean, that there should be only one way of processing the jobs until we have a good reason to define another class of jobs. It seems to me there is no such reason. That's why we should remove the ambiguities. In my opinion a job with missing information shouldn't be seen as such and therefore shouldn't be processed in the first place.

**Comment by eileen-kuehn** [comment]
Coming back to this question: I still would like to stick with jobs with incomplete information. The concept of the simulation is build around the fact that users sometimes don't provide complete or valid information. As such I also tend to process jobs that are incomplete in terms of information provided by the user as long as the person configuring the jobs takes care to provide complete information that the system will see at runtime. This ensures that we can model behaviour of a real system that does not have complete information in the first place. 
Further, this extension is build around the concept of caching. But in a real workflow we also have to consider jobs that don't have information of files being processed because they don't process any files next to jobs that actually require caching. So we expect jobs that behave differently. Internally they don't. It is just another collection of components being involved in processing the jobs.
So maybe I still don't really get the point why we should throw an exception or ignore jobs that are incomplete but still valid.
Maybe this might be linked to the issue we have when a job is given that exceeds available resources of all (currently available) sites. But this is probably another point of discussion that better belongs to the context of lapis.

**Comment by HerrHorizontal** [comment]
There might possibly be a better treatment than throwing an exception or filter these jobs out, if you want to keep them. Still, if there is some crucial information for a job missing, there is no point in simulating it, since this might lead to wrong results. To give an example in this specific case: If the file information is missing, how do you know whether there needs input-data to be transferred? If there is input-data which has to be transferred, this would also have implications on other jobs, which transfer data through the same connections, but you will never know. 

In my opinion, this ambiguous situation should be avoided. Therefore, it might be helpful for users to add some kind of safety shutdown to avoid this type of situation.

**Comment by eileen-kuehn** [comment]
In case there is no file information, the job is treated as a job, that does not require file transfers. If you intend the job to have file information, you need to provide it. The simulation cannot perform an educated guess what you meant to do. Especially as there will *always* be jobs that don't require file transfers.

So how do you want to tell the software that you are expecting information to be present without giving those information? Brain interfaces might be a great idea 😀 

So maybe I still don't get the point you are trying to make here.

**Comment by maxfischer2781** [comment]
So, the idea of having "file-less jobs" is so that we can always push background noise into the simulation, e.g. from regular LAPIS traces. Remember that plain LAPIS is just for jobs without transfers. Whether the simulation then treats them as having no data transfers at all, some averaged anonymous transfers, or whatever, can be programmed (though right now we go for "no transfers" for simplicity).

Ensuring that the job/cluster data is actually what the user wants to simulate is the responsibility of the user.

**Comment by HerrHorizontal** [comment]
One could easily solve this by still require the job to have an according parameter set, but to some default, none or empty value. This way you could keep the input structure and still treat jobs with no transfer.

**Comment by maxfischer2781** [comment]
I am not following. Requiring the parameter to be set would require changing every single job that does not have that parameter, so it would require changing the structure.

**Comment by eileen-kuehn** [comment]
Please also have in mind other extensions than the caching extension. Why should an extension being focused e.g. on scheduling require jobs to have information on input files? This is an burden you would put on each user no matter what kind of simulation or use case they have in mind. So I strongly argue for keeping it as is. If you prefer, you can change the `CachingJob` and the importer accordingly, so that each of them has this parameter set. But I don't prefer taking it into the core implementation of LAPIS.

**Comment by HerrHorizontal** [comment]
I think keeping it in the `CachingJob` is more than sufficient, since it is necessary for jobs in the caching context. I never intended to suggest changing it in the core.
